theme: jekyll-theme-minimal
title: Ahmed Elbashier
description: Cloud Engineer | Backend Developer | AI & CX Solutions Specialist
logo: /images/profile.jpg
show_downloads: false
github:
  is_project_page: false
